// conociendo prompt
/** prompt se usa para que el usuario pueda ingresar datos
 * realizar un algoritmo(serie de pasos) para que el usuario ingrese nombre y apellido
 * mostrarlo por consola y mostrarlo con una alerta
 *  pedir edad del usuario y sumarle 5 , mostrar el resultado en consola
 * 
 * 
 * 
 * 
 */

//respuesta ejercicio de ciclo, hay mas maneras de hacerlo: tarea encontrar otra forma de resolver , usando for o do while
let resultado= 7-2;
let entrada=31;
cont=1;
while (resultado<=entrada){
    resultado+=7
if(resultado<=entrada){
    resultado-=2
}
console.log(resultado)
cont++
}
console.log("respuesta "+cont)